SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%TablaVinculadaUNION%';

SELECT TOP 100 c.ID, v.OP
FROM ConCubo c
INNER JOIN TablaVinculadaUNION v
ON c.ID = v.OP;

SELECT TOP 100 * FROM ConCubo;
SELECT TOP 100 * FROM TablaVinculadaUNION;


